- name: "Deploy jenkins on docker"
  hosts: all
  gather_facts: true
  vars:
    jenkins_linux_user: "jenkins-user"
    jenkins_linux_pass: "CHANGE_ME"
    jenkins_workdir: "/opt/jenkins"
    jenkins_home_volume_dir: "/opt/jenkins/jenkins_home"

  tasks:
    - name: "Install dependent packages to Ubuntu"
      ansible.builtin.include_tasks: tasks/Install-dependent-packages-to-ubuntu.ansible.yaml
      when: ansible_distribution == "Ubuntu"

    - name: "Install dependent packages to CentOS"
      ansible.builtin.include_tasks: tasks/Install-dependent-packages-to-centos.ansible.yaml
      when: ansible_distribution == "CentOS"

    - name: "Create jenkins linux user"
      become: true
      ansible.builtin.user:
        name: "{{ jenkins_linux_user }}"
        shell: "/bin/bash"
        groups: "docker"
        state: present
        password: "{{ jenkins_linux_pass | password_hash('sha512') }}"

    - name: "Create jenkins workdir"
      become: true
      ansible.builtin.file:
        path: "{{ jenkins_workdir }}"
        state: directory
        mode: '0750'
        owner: "{{ jenkins_linux_user }}"
        group: "{{ jenkins_linux_user }}"

    - name: "Create jenkins home volume dir"
      become: true
      ansible.builtin.file:
        path: "{{ jenkins_home_volume_dir }}"
        state: directory
        mode: '0750'
        owner: 1000
        group: 1000

    - name: "Copy docker-compose files to the target host"
      become: true
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ jenkins_workdir }}"
        owner: "{{ jenkins_linux_user }}"
        group: "{{ jenkins_linux_user }}"
        mode: '0600'
      loop:
        - ".env"
        - "docker-compose.yml"

    - name: "Copy my-entrypoint file to the target host"
      become: true
      ansible.builtin.copy:
        src: "my-entrypoint.sh"
        dest: "{{ jenkins_workdir }}"
        owner: "{{ jenkins_linux_user }}"
        group: "{{ jenkins_linux_user }}"
        mode: '0755'

    - name: "Read .env file"
      ansible.builtin.slurp:
        src: files/.env
      delegate_to: localhost
      register: slurped_file

    - name: "Set fact with decoded content"
      ansible.builtin.set_fact:
        file_content: "{{ slurped_file.content | b64decode }}"

    - name: "Parse environment variables into a dictionary"
      ansible.builtin.set_fact:
        env_vars: "{{ env_vars | default({}) | combine({item.split('=')[0]: item.split('=')[1]}) }}"
      loop: "{{ file_content.splitlines() }}"
      when: item is search('=')

    - name: "Set jenkins image"
      ansible.builtin.set_fact:
        jenkins_image: "{{ env_vars.JENKINS_IMAGE }}"

    - name: "Debug jenkins image"
      ansible.builtin.debug:
        msg: "Jenkins image is: {{ jenkins_image }}"

    - name: "Pulling required docker image"
      become: true
      community.docker.docker_image:
        name: "{{ jenkins_image }}"
        source: pull

    - name: Start jenkins services
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ jenkins_workdir }}"
        state: present
